# Generated by Django 5.1 on 2024-09-19 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('Dept_no', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('Dept_name', models.CharField(max_length=100)),
                ('Dept_Loc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_no', models.PositiveIntegerField(max_length=5, primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=100)),
                ('Emp_Designation', models.CharField(max_length=50)),
                ('Emp_Salary', models.IntegerField()),
                ('dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
